version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: whatsapp-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-defaultpassword}
    volumes:
      - redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - whatsapp-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Opcional: Redis Commander para GUI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: whatsapp-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD:-defaultpassword}
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - whatsapp-network

volumes:
  redis-data:
    driver: local

networks:
  whatsapp-network:
    driver: bridge
