version: '3.8'

services:
  # Backend - WhatsApp Business API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    environment:
      # App Configuration
      - NODE_ENV=production
      - PORT=3002
      - LOG_LEVEL=${LOG_LEVEL:-info}
      
      # WhatsApp Business API
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WHATSAPP_API_VERSION=${WHATSAPP_API_VERSION:-v22.0}
      - WHATSAPP_BASE_URL=${WHATSAPP_BASE_URL:-https://graph.facebook.com}
      - WEBHOOK_VERIFY_TOKEN=${WEBHOOK_VERIFY_TOKEN}
      - WEBHOOK_PATH=${WEBHOOK_PATH:-/api/chat/webhook}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WHATSAPP_APP_SECRET=${WHATSAPP_APP_SECRET}
      
      # OpenRouter AI Configuration
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - OPEN_ROUTER_BASE_URL=${OPEN_ROUTER_BASE_URL:-https://openrouter.ai/api/v1}
      - OPEN_ROUTER_DEFAULT_MODEL=${OPEN_ROUTER_DEFAULT_MODEL:-google/gemini-flash-1.5}
      - DEFAULT_TEMPERATURE=${DEFAULT_TEMPERATURE:-0.7}
      - DEFAULT_MAX_TOKENS=${DEFAULT_MAX_TOKENS:-1000}
      - LLM_TIMEOUT_MS=${LLM_TIMEOUT_MS:-60000}
      
      # SOAP Services (Embler Integration)
      - EMBLER_WSDL_URL=${EMBLER_WSDL_URL}
      - EMBLER_ENDPOINT_URL=${EMBLER_ENDPOINT_URL}
      - TOKEN_CACHE_DURATION=${TOKEN_CACHE_DURATION:-10}
      - INVENTORY_CACHE_TTL=${INVENTORY_CACHE_TTL:-300000}
      - SOAP_CONNECTION_RETRIES=${SOAP_CONNECTION_RETRIES:-3}
      
      # POS Configuration
      - DEFAULT_POS_ID=${DEFAULT_POS_ID:-SAT}
      - VALID_POS_IDS=${VALID_POS_IDS:-ME,CUA,ECA,IZT,LIND,PORT,QRO,SAT,TPN,VC}
      - POS_CREDENTIALS=${POS_CREDENTIALS}
      
      # Supabase Configuration (Base de datos)
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE=${SUPABASE_SERVICE_ROLE}
      
      # Authentication
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-8h}
      - AUTHORIZED_USERS=${AUTHORIZED_USERS}
      - TEMP_PASSWORD=${TEMP_PASSWORD}
      
      # External APIs
      - API_NINJAS_KEY=${API_NINJAS_KEY}
      
      # CORS Configuration
      - CORS_ORIGINS=${CORS_ORIGINS}
      
      # Frontend/Backend URLs (CRÍTICAS para CORS y WebSocket)
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - PUBLIC_URL=${PUBLIC_URL}
      
      # Security Configuration
      - HOSTNAME=0.0.0.0
      - TRUST_PROXY=true
      - ENABLE_WEBHOOK_SIGNATURE=${ENABLE_WEBHOOK_SIGNATURE}
      
      # Rate Limiting (Enhanced)
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - RATE_LIMIT_AUTH_MAX=${RATE_LIMIT_AUTH_MAX:-20}
      - RATE_LIMIT_WEBHOOK_WINDOW=${RATE_LIMIT_WEBHOOK_WINDOW:-60000}
      - RATE_LIMIT_WEBHOOK_MAX=${RATE_LIMIT_WEBHOOK_MAX:-200}
      
      # Performance & Optimization (CRÍTICAS)
      - USE_DIRECT_SUPABASE=${USE_DIRECT_SUPABASE:-true}
      - USE_OPTIMIZED_QUERIES=${USE_OPTIMIZED_QUERIES:-true}
      - USE_BATCH_OPERATIONS=${USE_BATCH_OPERATIONS:-true}
      - USE_CIRCUIT_BREAKER=${USE_CIRCUIT_BREAKER:-true}
      - ENABLE_PERFORMANCE_METRICS=${ENABLE_PERFORMANCE_METRICS:-true}
      - ROLLBACK_THRESHOLD=${ROLLBACK_THRESHOLD:-10}
      - PERFORMANCE_MONITOR_INTERVAL=${PERFORMANCE_MONITOR_INTERVAL:-60000}
      
      # Realtime & Broadcasts (NUEVAS - CRÍTICAS)
      - ENABLE_REALTIME_BROADCASTS=${ENABLE_REALTIME_BROADCASTS:-true}
      - REALTIME_CHANNEL_PREFIX=${REALTIME_CHANNEL_PREFIX:-conversation}
      - REALTIME_PRESENCE_KEY=${REALTIME_PRESENCE_KEY:-users}
      - REALTIME_HEARTBEAT_INTERVAL=${REALTIME_HEARTBEAT_INTERVAL:-30000}
      - REALTIME_RECONNECT_DELAY=${REALTIME_RECONNECT_DELAY:-5000}
      - REALTIME_MAX_RECONNECT_ATTEMPTS=${REALTIME_MAX_RECONNECT_ATTEMPTS:-10}
      
      # Memory Management (CRÍTICAS)
      - MAX_MEMORY_USAGE=${MAX_MEMORY_USAGE:-80}
      - CRITICAL_MEMORY_USAGE=${CRITICAL_MEMORY_USAGE:-95}
      - MEMORY_CHECK_INTERVAL=${MEMORY_CHECK_INTERVAL:-60000}
      - CACHE_MAX_SIZE=${CACHE_MAX_SIZE:-1000}
      
      # Database Configuration (Extended)
      - SUPABASE_POOLING=${SUPABASE_POOLING:-true}
      - SUPABASE_MAX_CONNECTIONS=${SUPABASE_MAX_CONNECTIONS:-10}
      
      # Authentication (Extended)
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL:-admin@aova.mx}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD:-Agente2024!}
      
      # SOAP Configuration (Extended)
      - SOAP_CONNECTION_RETRIES=${SOAP_CONNECTION_RETRIES:-3}
      - LLM_TIMEOUT_MS=${LLM_TIMEOUT_MS:-60000}
      
      # System Configuration
      - ENABLE_DETAILED_LOGS=${ENABLE_DETAILED_LOGS:-false}
      
      # Error Handling & Monitoring (NUEVAS - CRÍTICAS)
      - ENABLE_ERROR_TRACKING=${ENABLE_ERROR_TRACKING:-true}
      - ERROR_NOTIFICATION_WEBHOOK=${ERROR_NOTIFICATION_WEBHOOK}
      - CRITICAL_ERROR_THRESHOLD=${CRITICAL_ERROR_THRESHOLD:-5}
      - ERROR_RECOVERY_ATTEMPTS=${ERROR_RECOVERY_ATTEMPTS:-3}
      
      # Failed Message Retry Service (NUEVAS)
      - ENABLE_FAILED_MESSAGE_RETRY=${ENABLE_FAILED_MESSAGE_RETRY:-true}
      - RETRY_INTERVAL_MS=${RETRY_INTERVAL_MS:-60000}
      - MAX_RETRY_ATTEMPTS=${MAX_RETRY_ATTEMPTS:-3}
      - RETRY_BACKOFF_MULTIPLIER=${RETRY_BACKOFF_MULTIPLIER:-2}
      
    restart: unless-stopped
    
    # Labels para SSL/HTTPS automático con Traefik
    labels:
      - "coolify.managed=true"
      - "coolify.version=4"
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      
      # Router HTTPS principal
      - "traefik.http.routers.wa-backend.rule=Host(`dev-apiwaprueba.aova.mx`)"
      - "traefik.http.routers.wa-backend.tls=true"
      - "traefik.http.routers.wa-backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wa-backend.entrypoints=websecure"
      
      # Service configuration
      - "traefik.http.services.wa-backend.loadbalancer.server.port=3002"
      
      # CORS middleware
      - "traefik.http.middlewares.wa-backend-cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.wa-backend-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.wa-backend-cors.headers.accesscontrolalloworiginlist=https://dev-waprueba.aova.mx"
      - "traefik.http.middlewares.wa-backend-cors.headers.accesscontrolallowcredentials=true"
      
      # Apply middleware
      - "traefik.http.routers.wa-backend.middlewares=wa-backend-cors"
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Configuración de recursos
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 30s
    
    # Configuración de red y seguridad
    networks:
      - coolify

  # Frontend - React WhatsApp Business Panel
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    environment:
      # App Configuration
      - NODE_ENV=production
      - PORT=80
      
      # Backend API Connection - IMPORTANTE: Debe apuntar a la URL pública del backend
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-https://dev-apiwaprueba.aova.mx}
      
      # Supabase Frontend Access (Para realtime)
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      
      # Alternative API URLs
      - VITE_API_URL=${VITE_API_URL:-https://dev-apiwaprueba.aova.mx}
      
      # Frontend Logging
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-warn}
      
      # Realtime Configuration (NUEVAS - CRÍTICAS para frontend)
      - VITE_ENABLE_REALTIME=${VITE_ENABLE_REALTIME:-true}
      - VITE_REALTIME_CHANNEL_PREFIX=${VITE_REALTIME_CHANNEL_PREFIX:-conversation}
      - VITE_REALTIME_HEARTBEAT_INTERVAL=${VITE_REALTIME_HEARTBEAT_INTERVAL:-30000}
      - VITE_REALTIME_RECONNECT_DELAY=${VITE_REALTIME_RECONNECT_DELAY:-5000}
      - VITE_MAX_RECONNECT_ATTEMPTS=${VITE_MAX_RECONNECT_ATTEMPTS:-10}
      
      # Performance & Optimization (NUEVAS para frontend)
      - VITE_USE_OPTIMISTIC_UPDATES=${VITE_USE_OPTIMISTIC_UPDATES:-true}
      - VITE_MESSAGE_BATCH_SIZE=${VITE_MESSAGE_BATCH_SIZE:-50}
      - VITE_CACHE_DURATION_MS=${VITE_CACHE_DURATION_MS:-300000}
      
    restart: unless-stopped
    
    # Labels para SSL/HTTPS automático con Traefik
    labels:
      - "coolify.managed=true"
      - "coolify.version=4"
      - "traefik.enable=true"
      - "traefik.docker.network=coolify"
      
      # Router HTTPS principal
      - "traefik.http.routers.wa-frontend.rule=Host(`dev-waprueba.aova.mx`)"
      - "traefik.http.routers.wa-frontend.tls=true"
      - "traefik.http.routers.wa-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wa-frontend.entrypoints=websecure"
      
      # Service configuration
      - "traefik.http.services.wa-frontend.loadbalancer.server.port=80"
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Configuración de recursos
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Configuración de red y seguridad
    networks:
      - coolify

networks:
  coolify:
    external: true